# Simple Customer Data ETL Pipeline
# Uses template inheritance with minimal customization

template:
  extends: daily_etl

dag_id: etl_customer_simple
description: "Simple customer data ETL using template inheritance"
tags: [customer, simple]

# Environment-specific configurations
environments:
  dev:
    schedule: "@once"  # Manual trigger in dev
    start_date: "2024-09-01"
    email: ["dev-team@company.com"]
          
  prod:
    schedule: "0 1 * * *"  # 1 AM daily in production
    start_date: "2024-01-01"
    email: ["data-team@company.com"]

# Override specific task parameters using template overrides
template:
  extends: daily_etl
  overrides:
    "tasks.0.parameters.python_callable": "etl.customer.extract_customer_data"
    "tasks.1.parameters.python_callable": "etl.customer.transform_customer_data"
    "tasks.2.parameters.python_callable": "etl.customer.load_customer_data"

# Customer data assets
assets:
  consumes:
    - "postgres://crm/customers"
  produces:
    - "snowflake://warehouse/dim_customers"
